name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set up JDK 11

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository  # Cache Maven dependencies to speed up builds
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.java') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests  # Build the project using Maven

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .  # Build the Docker image
        docker tag ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Tag the image as latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}  # Push the image with commit hash tag
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Push the image with latest tag
